export const Types = {
	GET_USERS: "GET_USERS",
	CUR_USER: "CUR_USER",
	LOGIN_STATUS: "LOGIN_STATUS",
	ADD_CUSTOMER: "ADD_CUTOMER",
	GET_CUSTOMERS: "GET_CUSTOMERS",
	ADD_AREA: "ADD_AREA",
	GET_AREAS: "GET_AREAS",
};
