export const labels = {
	SIGNIN: "Sign In",
	SIGNOUT: "Sign Out",
	CUSTOMER: "Customer",
	CUSTOMERS: "Customers",
	NEW_CUSTOMER: "New Customer",
	ADMIN: "ADMIN",
	LMS_USER: "LMS_USER",
	NEW_AREA: "New Area",
	ADD_AREA: "Add Area",
	NEW_PERMISSION: "New Permission",
	ADD_PERMISSION: "Add Permission",
	NEW_ROLE: "New Role",
	ADD_ROLE: "Add Role",
};
